### ISSUE TITLE
知乎网址转换出错

### ISSUE THREAD

**Issue by LvShuaiChao** [yoyooyooo/pure-post#1]
为什么这个网址打开会出错呢？
https://pure-post.vercel.app/api/index?url=https://zhuanlan.zhihu.com/p/358236220$markdownHTML=1
![image](https://user-images.githubusercontent.com/35528109/119334716-03e3c900-bcbe-11eb-8485-4c4a792fedc1.png)

**Comment by yoyooyooo** [comment]
抱歉才看到。你 url 输错了，应该是：
> `https://pure-post.vercel.app/api/index?url=https://zhuanlan.zhihu.com/p/358236220&markdownHTML=1`

参数用 `&` 分割
